"""Генерирует TS-файл справочных данных для фронтенда из бэкенд-данных.

Единственный источник истины — backend/app/data. Фронтенд использует
сгенерированный файл для мгновенного показа классики и вычисления гексаграммы
без обращения к API. Запуск:  python scripts/export_frontend_data.py
"""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))  # backend/

from app.data.hexagrams import HEXAGRAMS, KING_WEN  # noqa: E402
from app.data.trigrams import TRIGRAMS  # noqa: E402


def js(obj) -> str:
    return json.dumps(obj, ensure_ascii=False, indent=2)


trigrams = {k: {**v, "lines": list(v["lines"])} for k, v in TRIGRAMS.items()}

content = f"""// AUTO-GENERATED by backend/scripts/export_frontend_data.py — не редактировать вручную.
export interface Trigram {{
  id: string; name: string; hanzi: string; lines: number[];
  image: string; action: string; family: string;
  element: string; direction: string; classic: string;
}}
export interface Hexagram {{
  number: number; lower: string; upper: string;
  name: string; title: string; essence: string;
}}

export const TRIGRAMS: Record<string, Trigram> = {js(trigrams)};

export const HEXAGRAMS: Record<number, Hexagram> = {js(HEXAGRAMS)};

export const KING_WEN: Record<string, Record<string, number>> = {js(KING_WEN)};

export const TRIGRAM_ORDER: string[] = {js(list(TRIGRAMS.keys()))};

export function hexagramNumber(lower: string, upper: string): number {{
  return KING_WEN[lower][upper];
}}
"""

target = (
    pathlib.Path(__file__).resolve().parents[2]
    / "frontend" / "src" / "data" / "reference.generated.ts"
)
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(content, encoding="utf-8")
print("wrote", target)
