// AUTO-GENERATED by backend/scripts/export_frontend_data.py — не редактировать вручную.
export interface Trigram {
  id: string; name: string; hanzi: string; lines: number[];
  image: string; action: string; family: string;
  element: string; direction: string; classic: string;
}
export interface Hexagram {
  number: number; lower: string; upper: string;
  name: string; title: string; essence: string;
}

export const TRIGRAMS: Record<string, Trigram> = {
  "qian": {
    "id": "qian",
    "name": "Цянь",
    "hanzi": "乾",
    "lines": [
      1,
      1,
      1
    ],
    "image": "Небо",
    "action": "Творчество",
    "family": "Отец",
    "element": "Металл",
    "direction": "Северо-запад",
    "classic": "[TODO Таня]"
  },
  "kun": {
    "id": "kun",
    "name": "Кунь",
    "hanzi": "坤",
    "lines": [
      0,
      0,
      0
    ],
    "image": "Земля",
    "action": "Исполнение",
    "family": "Мать",
    "element": "Почва",
    "direction": "Юго-запад",
    "classic": "[TODO Таня]"
  },
  "zhen": {
    "id": "zhen",
    "name": "Чжэнь",
    "hanzi": "震",
    "lines": [
      1,
      0,
      0
    ],
    "image": "Гром",
    "action": "Возбуждение",
    "family": "Старший сын",
    "element": "Дерево",
    "direction": "Восток",
    "classic": "[TODO Таня]"
  },
  "xun": {
    "id": "xun",
    "name": "Сюнь",
    "hanzi": "巽",
    "lines": [
      0,
      1,
      1
    ],
    "image": "Ветер",
    "action": "Проникновение",
    "family": "Старшая дочь",
    "element": "Дерево",
    "direction": "Юго-восток",
    "classic": "[TODO Таня]"
  },
  "kan": {
    "id": "kan",
    "name": "Кань",
    "hanzi": "坎",
    "lines": [
      0,
      1,
      0
    ],
    "image": "Вода",
    "action": "Погружение",
    "family": "Средний сын",
    "element": "Вода",
    "direction": "Север",
    "classic": "[TODO Таня]"
  },
  "li": {
    "id": "li",
    "name": "Ли",
    "hanzi": "離",
    "lines": [
      1,
      0,
      1
    ],
    "image": "Огонь",
    "action": "Сцепление",
    "family": "Средняя дочь",
    "element": "Огонь",
    "direction": "Юг",
    "classic": "[TODO Таня]"
  },
  "gen": {
    "id": "gen",
    "name": "Гэнь",
    "hanzi": "艮",
    "lines": [
      0,
      0,
      1
    ],
    "image": "Гора",
    "action": "Незыблемость",
    "family": "Младший сын",
    "element": "Почва",
    "direction": "Северо-восток",
    "classic": "[TODO Таня]"
  },
  "dui": {
    "id": "dui",
    "name": "Дуй",
    "hanzi": "兌",
    "lines": [
      1,
      1,
      0
    ],
    "image": "Водоём",
    "action": "Разрешение",
    "family": "Младшая дочь",
    "element": "Металл",
    "direction": "Запад",
    "classic": "[TODO Таня]"
  }
};

export const HEXAGRAMS: Record<number, Hexagram> = {
  "1": {
    "number": 1,
    "lower": "qian",
    "upper": "qian",
    "name": "Цянь",
    "title": "Творчество",
    "essence": "[TODO Таня]"
  },
  "2": {
    "number": 2,
    "lower": "kun",
    "upper": "kun",
    "name": "Кунь",
    "title": "Исполнение",
    "essence": "[TODO Таня]"
  },
  "3": {
    "number": 3,
    "lower": "zhen",
    "upper": "kan",
    "name": "Чжунь",
    "title": "Начальная трудность",
    "essence": "[TODO Таня]"
  },
  "4": {
    "number": 4,
    "lower": "kan",
    "upper": "gen",
    "name": "Мэн",
    "title": "Недоразвитость",
    "essence": "[TODO Таня]"
  },
  "5": {
    "number": 5,
    "lower": "qian",
    "upper": "kan",
    "name": "Сюй",
    "title": "Необходимость ждать",
    "essence": "[TODO Таня]"
  },
  "6": {
    "number": 6,
    "lower": "kan",
    "upper": "qian",
    "name": "Сун",
    "title": "Тяжба",
    "essence": "[TODO Таня]"
  },
  "7": {
    "number": 7,
    "lower": "kan",
    "upper": "kun",
    "name": "Ши",
    "title": "Войско",
    "essence": "[TODO Таня]"
  },
  "8": {
    "number": 8,
    "lower": "kun",
    "upper": "kan",
    "name": "Би",
    "title": "Приближение",
    "essence": "[TODO Таня]"
  },
  "9": {
    "number": 9,
    "lower": "qian",
    "upper": "xun",
    "name": "Сяо чу",
    "title": "Воспитание малым",
    "essence": "[TODO Таня]"
  },
  "10": {
    "number": 10,
    "lower": "dui",
    "upper": "qian",
    "name": "Ли",
    "title": "Наступление",
    "essence": "[TODO Таня]"
  },
  "11": {
    "number": 11,
    "lower": "qian",
    "upper": "kun",
    "name": "Тай",
    "title": "Расцвет",
    "essence": "[TODO Таня]"
  },
  "12": {
    "number": 12,
    "lower": "kun",
    "upper": "qian",
    "name": "Пи",
    "title": "Упадок",
    "essence": "[TODO Таня]"
  },
  "13": {
    "number": 13,
    "lower": "li",
    "upper": "qian",
    "name": "Тун жэнь",
    "title": "Родня",
    "essence": "[TODO Таня]"
  },
  "14": {
    "number": 14,
    "lower": "qian",
    "upper": "li",
    "name": "Да ю",
    "title": "Владение многим",
    "essence": "[TODO Таня]"
  },
  "15": {
    "number": 15,
    "lower": "gen",
    "upper": "kun",
    "name": "Цянь",
    "title": "Смирение",
    "essence": "[TODO Таня]"
  },
  "16": {
    "number": 16,
    "lower": "kun",
    "upper": "zhen",
    "name": "Юй",
    "title": "Вольность",
    "essence": "[TODO Таня]"
  },
  "17": {
    "number": 17,
    "lower": "zhen",
    "upper": "dui",
    "name": "Суй",
    "title": "Последование",
    "essence": "[TODO Таня]"
  },
  "18": {
    "number": 18,
    "lower": "xun",
    "upper": "gen",
    "name": "Гу",
    "title": "Исправление порчи",
    "essence": "[TODO Таня]"
  },
  "19": {
    "number": 19,
    "lower": "dui",
    "upper": "kun",
    "name": "Линь",
    "title": "Посещение",
    "essence": "[TODO Таня]"
  },
  "20": {
    "number": 20,
    "lower": "kun",
    "upper": "xun",
    "name": "Гуань",
    "title": "Созерцание",
    "essence": "[TODO Таня]"
  },
  "21": {
    "number": 21,
    "lower": "zhen",
    "upper": "li",
    "name": "Ши хо",
    "title": "Стиснутые зубы",
    "essence": "[TODO Таня]"
  },
  "22": {
    "number": 22,
    "lower": "li",
    "upper": "gen",
    "name": "Би",
    "title": "Убранство",
    "essence": "[TODO Таня]"
  },
  "23": {
    "number": 23,
    "lower": "kun",
    "upper": "gen",
    "name": "Бо",
    "title": "Разрушение",
    "essence": "[TODO Таня]"
  },
  "24": {
    "number": 24,
    "lower": "zhen",
    "upper": "kun",
    "name": "Фу",
    "title": "Возврат",
    "essence": "[TODO Таня]"
  },
  "25": {
    "number": 25,
    "lower": "zhen",
    "upper": "qian",
    "name": "У ван",
    "title": "Беспорочность",
    "essence": "[TODO Таня]"
  },
  "26": {
    "number": 26,
    "lower": "qian",
    "upper": "gen",
    "name": "Да чу",
    "title": "Воспитание великим",
    "essence": "[TODO Таня]"
  },
  "27": {
    "number": 27,
    "lower": "zhen",
    "upper": "gen",
    "name": "И",
    "title": "Питание",
    "essence": "[TODO Таня]"
  },
  "28": {
    "number": 28,
    "lower": "xun",
    "upper": "dui",
    "name": "Да го",
    "title": "Переразвитие великого",
    "essence": "[TODO Таня]"
  },
  "29": {
    "number": 29,
    "lower": "kan",
    "upper": "kan",
    "name": "Кань",
    "title": "Бездна",
    "essence": "[TODO Таня]"
  },
  "30": {
    "number": 30,
    "lower": "li",
    "upper": "li",
    "name": "Ли",
    "title": "Сияние",
    "essence": "[TODO Таня]"
  },
  "31": {
    "number": 31,
    "lower": "gen",
    "upper": "dui",
    "name": "Сянь",
    "title": "Сочетание",
    "essence": "[TODO Таня]"
  },
  "32": {
    "number": 32,
    "lower": "xun",
    "upper": "zhen",
    "name": "Хэн",
    "title": "Постоянство",
    "essence": "[TODO Таня]"
  },
  "33": {
    "number": 33,
    "lower": "gen",
    "upper": "qian",
    "name": "Дунь",
    "title": "Бегство",
    "essence": "[TODO Таня]"
  },
  "34": {
    "number": 34,
    "lower": "qian",
    "upper": "zhen",
    "name": "Да чжуан",
    "title": "Мощь великого",
    "essence": "[TODO Таня]"
  },
  "35": {
    "number": 35,
    "lower": "kun",
    "upper": "li",
    "name": "Цзинь",
    "title": "Восход",
    "essence": "[TODO Таня]"
  },
  "36": {
    "number": 36,
    "lower": "li",
    "upper": "kun",
    "name": "Мин и",
    "title": "Поражение света",
    "essence": "[TODO Таня]"
  },
  "37": {
    "number": 37,
    "lower": "li",
    "upper": "xun",
    "name": "Цзя жэнь",
    "title": "Домашние",
    "essence": "[TODO Таня]"
  },
  "38": {
    "number": 38,
    "lower": "dui",
    "upper": "li",
    "name": "Куй",
    "title": "Разлад",
    "essence": "[TODO Таня]"
  },
  "39": {
    "number": 39,
    "lower": "gen",
    "upper": "kan",
    "name": "Цзянь",
    "title": "Препятствие",
    "essence": "[TODO Таня]"
  },
  "40": {
    "number": 40,
    "lower": "kan",
    "upper": "zhen",
    "name": "Цзе",
    "title": "Разрешение",
    "essence": "[TODO Таня]"
  },
  "41": {
    "number": 41,
    "lower": "dui",
    "upper": "gen",
    "name": "Сунь",
    "title": "Убыль",
    "essence": "[TODO Таня]"
  },
  "42": {
    "number": 42,
    "lower": "zhen",
    "upper": "xun",
    "name": "И",
    "title": "Приумножение",
    "essence": "[TODO Таня]"
  },
  "43": {
    "number": 43,
    "lower": "qian",
    "upper": "dui",
    "name": "Гуай",
    "title": "Выход",
    "essence": "[TODO Таня]"
  },
  "44": {
    "number": 44,
    "lower": "xun",
    "upper": "qian",
    "name": "Гоу",
    "title": "Перечение",
    "essence": "[TODO Таня]"
  },
  "45": {
    "number": 45,
    "lower": "kun",
    "upper": "dui",
    "name": "Цуй",
    "title": "Воссоединение",
    "essence": "[TODO Таня]"
  },
  "46": {
    "number": 46,
    "lower": "xun",
    "upper": "kun",
    "name": "Шэн",
    "title": "Подъём",
    "essence": "[TODO Таня]"
  },
  "47": {
    "number": 47,
    "lower": "kan",
    "upper": "dui",
    "name": "Кунь",
    "title": "Истощение",
    "essence": "[TODO Таня]"
  },
  "48": {
    "number": 48,
    "lower": "xun",
    "upper": "kan",
    "name": "Цзин",
    "title": "Колодец",
    "essence": "[TODO Таня]"
  },
  "49": {
    "number": 49,
    "lower": "li",
    "upper": "dui",
    "name": "Гэ",
    "title": "Смена",
    "essence": "[TODO Таня]"
  },
  "50": {
    "number": 50,
    "lower": "xun",
    "upper": "li",
    "name": "Дин",
    "title": "Жертвенник",
    "essence": "[TODO Таня]"
  },
  "51": {
    "number": 51,
    "lower": "zhen",
    "upper": "zhen",
    "name": "Чжэнь",
    "title": "Возбуждение",
    "essence": "[TODO Таня]"
  },
  "52": {
    "number": 52,
    "lower": "gen",
    "upper": "gen",
    "name": "Гэнь",
    "title": "Сосредоточенность",
    "essence": "[TODO Таня]"
  },
  "53": {
    "number": 53,
    "lower": "gen",
    "upper": "xun",
    "name": "Цзянь",
    "title": "Течение",
    "essence": "[TODO Таня]"
  },
  "54": {
    "number": 54,
    "lower": "dui",
    "upper": "zhen",
    "name": "Гуй мэй",
    "title": "Невеста",
    "essence": "[TODO Таня]"
  },
  "55": {
    "number": 55,
    "lower": "li",
    "upper": "zhen",
    "name": "Фэн",
    "title": "Изобилие",
    "essence": "[TODO Таня]"
  },
  "56": {
    "number": 56,
    "lower": "gen",
    "upper": "li",
    "name": "Люй",
    "title": "Странствие",
    "essence": "[TODO Таня]"
  },
  "57": {
    "number": 57,
    "lower": "xun",
    "upper": "xun",
    "name": "Сюнь",
    "title": "Проникновение",
    "essence": "[TODO Таня]"
  },
  "58": {
    "number": 58,
    "lower": "dui",
    "upper": "dui",
    "name": "Дуй",
    "title": "Радость",
    "essence": "[TODO Таня]"
  },
  "59": {
    "number": 59,
    "lower": "kan",
    "upper": "xun",
    "name": "Хуань",
    "title": "Раздробление",
    "essence": "[TODO Таня]"
  },
  "60": {
    "number": 60,
    "lower": "dui",
    "upper": "kan",
    "name": "Цзе",
    "title": "Ограничение",
    "essence": "[TODO Таня]"
  },
  "61": {
    "number": 61,
    "lower": "dui",
    "upper": "xun",
    "name": "Чжун фу",
    "title": "Внутренняя правда",
    "essence": "[TODO Таня]"
  },
  "62": {
    "number": 62,
    "lower": "gen",
    "upper": "zhen",
    "name": "Сяо го",
    "title": "Переразвитие малого",
    "essence": "[TODO Таня]"
  },
  "63": {
    "number": 63,
    "lower": "li",
    "upper": "kan",
    "name": "Цзи цзи",
    "title": "Уже конец",
    "essence": "[TODO Таня]"
  },
  "64": {
    "number": 64,
    "lower": "kan",
    "upper": "li",
    "name": "Вэй цзи",
    "title": "Ещё не конец",
    "essence": "[TODO Таня]"
  }
};

export const KING_WEN: Record<string, Record<string, number>> = {
  "qian": {
    "qian": 1,
    "kan": 5,
    "xun": 9,
    "kun": 11,
    "li": 14,
    "gen": 26,
    "zhen": 34,
    "dui": 43
  },
  "kun": {
    "kun": 2,
    "kan": 8,
    "qian": 12,
    "zhen": 16,
    "xun": 20,
    "gen": 23,
    "li": 35,
    "dui": 45
  },
  "zhen": {
    "kan": 3,
    "dui": 17,
    "li": 21,
    "kun": 24,
    "qian": 25,
    "gen": 27,
    "xun": 42,
    "zhen": 51
  },
  "kan": {
    "gen": 4,
    "qian": 6,
    "kun": 7,
    "kan": 29,
    "zhen": 40,
    "dui": 47,
    "xun": 59,
    "li": 64
  },
  "dui": {
    "qian": 10,
    "kun": 19,
    "li": 38,
    "gen": 41,
    "zhen": 54,
    "dui": 58,
    "kan": 60,
    "xun": 61
  },
  "li": {
    "qian": 13,
    "gen": 22,
    "li": 30,
    "kun": 36,
    "xun": 37,
    "dui": 49,
    "zhen": 55,
    "kan": 63
  },
  "gen": {
    "kun": 15,
    "dui": 31,
    "qian": 33,
    "kan": 39,
    "gen": 52,
    "xun": 53,
    "li": 56,
    "zhen": 62
  },
  "xun": {
    "gen": 18,
    "dui": 28,
    "zhen": 32,
    "qian": 44,
    "kun": 46,
    "kan": 48,
    "li": 50,
    "xun": 57
  }
};

export const TRIGRAM_ORDER: string[] = [
  "qian",
  "kun",
  "zhen",
  "xun",
  "kan",
  "li",
  "gen",
  "dui"
];

export function hexagramNumber(lower: string, upper: string): number {
  return KING_WEN[lower][upper];
}
